# Generated by Django 4.1.4 on 2023-01-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userregister',
            fields=[
                ('email', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'userRegister',
                'managed': False,
            },
        ),
    ]
